### ISSUE TITLE
workflow outputs

### ISSUE THREAD

**Issue by warsmit** [convictional/trigger-workflow-and-wait#15]
Hello.
Thank for the workflow. Can you answer my questions, please?
- Can you add in outputs a URL link on workflow what we launch?
- How to write launch results, URL in PR?

**Comment by yurist38** [comment]
The first one is totally needed! The link to the triggered workflow has to be in the output. It will simplify debugging a lot!

But the action is great actually, thanks for developing it!

**Comment by keithconvictional** [comment]
Closing with this change; https://github.com/convictional/trigger-workflow-and-wait/pull/14
