### ISSUE TITLE
The action does not wait for the triggered workflow anymore

### ISSUE THREAD

**Issue by yurist38** [convictional/trigger-workflow-and-wait#16]
Hey guys! It seems like something went wrong after releasing version 1.4.0. I just switched to v.1.5.0 after using 1.3.0 and realized that the action is not waiting for the triggered workflow anymore... I have tested v 1.4.0 - the same issue. Downgrading to v 1.3.0 solves the problem. But I need the feature from the latest release. 😄 

Please take a look, maybe you can find a quick solution? Can you reproduce it at all? 🤔 

Here's the screenshot of my output:
![Screen Shot 2021-07-27 at 16 11 58](https://user-images.githubusercontent.com/10692413/127169557-bd88cc06-640d-4e82-9cf4-8c71e6ccca4b.png)

**Comment by Lurrobert** [comment]
Same here

**Comment by yurist38** [comment]
Thanks for confirming the issue @Lurrobert ! I just checked again the PR that was merged before v1.4 (#7). It's mostly refactoring around the env var's syntax. But I found this change suspicious, it's might be the cause of the issue: https://github.com/convictional/trigger-workflow-and-wait/pull/7/files#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2L88 . Lines 88-89 were deleted, and that's why the waiting logic has disappeared I guess...

**Comment by kayla-barenz-kr** [comment]
Is there any update on this? I am experiencing the same thing.

**Comment by yurist38** [comment]
I see that my PR #17 got merged 8 days ago but the new version is not released yet. I guess that's the problem. As an option, you can use the code from the `master` branch, it should work I believe.

```
uses: convictional/trigger-workflow-and-wait@master
```

Do you guys plan to release a new version by the way?

**Comment by Sangeetha21** [comment]
<img width="1400" alt="Screenshot 2021-11-12 at 2 30 34 PM" src="https://user-images.githubusercontent.com/20011821/141457750-d53eeb15-0a64-467c-92bd-d483763d75b2.png">

Hi, I am not getting any id where I could see that curl message "curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream",
Can someone Please say if I am missing something?

**Comment by tfgstudios** [comment]
I have this problem too. Can you fix it, please?

**Comment by envil** [comment]
Revert to 1.3.0 resolved the issue.
