### ISSUE TITLE
wait_interval cannot be set

### ISSUE THREAD

**Issue by patrick1990** [convictional/trigger-workflow-and-wait#19]
It's seems that I cannot set the wait_interval to a custom value. If I set it to 20 in my github workflow, it still uses the default of 10 seconds.

I'm pretty new to github actions, but I would guess the problem is, that [entrypoint.sh#L16](https://github.com/convictional/trigger-workflow-and-wait/blob/6b790788cfa74eeb51ae7cc82560e885189e616b/entrypoint.sh#L16) wants to read the environment variable "INPUT_WAIT**ING**_INTERVAL" instead of the declared action input wait_interval in [action.yml#L35](https://github.com/convictional/trigger-workflow-and-wait/blob/6b790788cfa74eeb51ae7cc82560e885189e616b/action.yml#L35).

**Comment by MarkoSagadin** [comment]
Yes, @patrick1990 you are correct, I just check the documentation; which says that a lowercase input variable is converted to uppercase and prepended with "INPUT_". I hope for a quick fix :)

**Comment by smfeest** [comment]
It looks like this is the issue addressed by the first commit in #34. Perhaps there's a case for cherry picking that fix separately if the rest of the PR isn't ready for release?
