### ISSUE TITLE
Warning with custom waiting interval value

### ISSUE THREAD

**Issue by joelguittet** [convictional/trigger-workflow-and-wait#35]
Hello,

While executing this with custom waiting interval set to 180seconds, i have the following waning:

```
Warning: Unexpected input(s) 'waiting_interval', valid inputs are ['entryPoint', 'args', 'owner', 'repo', 'github_token', 'ref', 'wait_interval', 'workflow_file_name', 'inputs', 'propagate_failure', 'trigger_workflow', 'wait_workflow']
```

Version: 1.3.0 (the next versions have an issue, the step do not wait for the distant workflow to finish, so i have to keep 1.3.0, I can't upgrade).

Joel

**Comment by duhow** [comment]
There's a new feature `last_workflow_interval` in [v1.6.0](https://github.com/convictional/trigger-workflow-and-wait/tree/v1.6.0), maybe it could help you?

**Comment by rabih** [comment]
@joelguittet There was a rename of waiting_interval to wait_interval (see this [commit](https://github.com/convictional/trigger-workflow-and-wait/commit/8be90d7fe2a493a88008ef6d9b9d1d71907ae9a7#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2R21))
I am in the process of pushing up a new release that addresses this missing functionality.

@duhow last_workflow_interval appears to not actually do anything and will be removed

**Comment by rabih** [comment]
@joelguittet give it a shot :)
