### ISSUE TITLE
Update wait_interval input to waiting_interval

### ISSUE THREAD

**Issue by namarora** [convictional/trigger-workflow-and-wait#43]
The below input needs to be updated as a warning is thrown `Unexpected input(s) 'waiting_interval', valid inputs are ['entryPoint', 'args', 'owner', 'repo', 'github_token', 'ref', 'wait_interval', 'workflow_file_name', 'inputs', 'propagate_failure', 'trigger_workflow', 'wait_workflow']`
https://github.com/convictional/trigger-workflow-and-wait/blob/ceed17de92642e7effd01d5c23c3c1247ed0ec27/action.yml#L23

**Comment by keithconvictional** [comment]
Closing, this has been fixed in v1.6.0. Thanks for the feedback.
