### ISSUE TITLE
Incorrect behaviour for triggering workflow with missing input

### ISSUE THREAD

**Issue by envil** [convictional/trigger-workflow-and-wait#44]
**Expected behaviour**
- When triggering a workflow, if the required inputs of the workflow are missing, the action should throw an error.

**Current behaviour**
- When triggering a workflow, if the required inputs of the workflow are missing, the action did not throw any error

Action version: 1.3.0

**Comment by keithweaver** [comment]
I'll look into this. This is true too, Bug: "message": "No ref found for: main" --> Should fail

**Comment by keithconvictional** [comment]
Confirm that this fails. Copy and paste from a test pipeline. Closing:

```
curl: (22) The requested URL returned error: 422
api failed:
path: workflows/deploy.yml/dispatches
response: {
  "message": "No ref found for: fail",
  "documentation_url": "https://docs.github.com/rest/reference/actions#create-a-workflow-dispatch-event"
}
```
