### ISSUE TITLE
always getting 404 when triggering the downstream job

### ISSUE THREAD

**Issue by kalkir** [convictional/trigger-workflow-and-wait#54]
Hi, 

When I tried to trigger another repo job, I am always getting 404, I have manually run the job using curl command to https://api.github.com it executed well. I am using correct github token, owner, user. 

when I looked the entrypoint script the curl command is different, I had to pass -d '{"ref":"main"}', headers that I am passing are 
-H "Authorization: token ", -H "Accept: application/vnd.github.v3+json" , I noticed in the entrypoint it is using Bearer token. 
Can you help me to resolve the issue.

**Comment by rabih** [comment]
@kalkir are you passing the authorization header as `"Authorization: token <insert github/bearer token>"?

**Comment by kalkir** [comment]
Yes, that is correct.

**Comment by rabih** [comment]
Could you supply the curl command (less private details)

**Comment by rabih** [comment]
Gonna close this issue due to inactivity
