### ISSUE TITLE
curl returns 502 randomly

### ISSUE THREAD

**Issue by witekio-kwe** [convictional/trigger-workflow-and-wait#55]
```
Checking conclusion [null]
Checking status [queued]
Sleeping for 10 seconds
Checking conclusion [null]
Checking status [queued]
curl: (22) The requested URL returned error: 502
api failed:
path: runs/2830763366
response: {
  "message": "Server Error"
}
```

this can be seen randomly, making the pipeline fail, even though the called workflow is still running and fine.
From my perspective it would be safe to ignore error 5xx

**Comment by rabih** [comment]
@keithconvictional thoughts on this?

**Comment by keithconvictional** [comment]
@rabih I guess worst case scenario it runs till the API returns to a healthy state. I agree with it.
